name: Build and Package

on:
  push:
    branches:
      - unstable
  pull_request:
    branches:
      - unstable

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        make

    - name: Package
      run: |
        tar -czvf redis-linux.tar.gz .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: redis-linux
        path: redis-linux.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Locate solution file
      run: |
        Get-ChildItem -Path . -Recurse -Filter *.sln

    - name: Build
      run: |
        msbuild deps/jemalloc/msvc/jemalloc_vc2017.sln /p:Configuration=Release

    - name: Package
      run: |
        tar -czvf redis-windows.tar.gz .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: redis-windows
        path: redis-windows.tar.gz
